[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/"
  to = "https://blog.gosocial.io"

[[redirects]]
  from = "/blog"
  to = "https://blog.gosocial.io"

[[redirects]]
  from = "/gosocial-challenge-contributors"
  to = "https://blog.gosocial.io/contributors"

[[redirects]]
  from = "/privacy-policy.html"
  to = "https://blog.gosocial.io/privacy-policy.html"

[[redirects]]
  from = "/gosocial-challenge-contributors"
  to = "https://blog.gosocial.io/contributors"